window.QUESTIONS = [
  // POWER TOOLS / EQUIPMENT
  {
    id: 1,
    text: "Cordless drill/driver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 2,
    text: "Impact driver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 3,
    text: "Corded drill is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 4,
    text: "Screw gun is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 5,
    text: "Circular saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 6,
    text: "Reciprocating saw (Sawzall) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 7,
    text: "Jigsaw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 8,
    text: "Miter saw (chop saw) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 9,
    text: "Table saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 10,
    text: "Angle grinder is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 11,
    text: "Belt sander is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 12,
    text: "Oscillating multi-tool is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 13,
    text: "Rotary hammer / hammer drill is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 14,
    text: "Spade bit (drill bit) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 15,
    text: "Magnetic bit holder / nut driver adapter is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 16,
    text: "Hole saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 17,
    text: "Portable band saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 18,
    text: "Mini excavator is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 19,
    text: "Backhoe loader is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 20,
    text: "Bulldozer is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 21,
    text: "Asphalt paver / paving machine is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 22,
    text: "Worm drive circular saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 23,
    text: "Hypoid drive circular saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 24,
    text: "Sidewinder / direct-drive circular saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 25,
    text: "Angle-head drill motor is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 26,
    text: "Pistol-grip drill motor is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 27,
    text: "Band saw (stationary) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 28,
    text: "Auger bit is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 29,
    text: "Multi-spur bit is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 30,
    text: "Twist drill bit is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 31,
    text: "Boom lift is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 32,
    text: "GFI protector is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },
  {
    id: 33,
    text: "‘Spider’ power distribution box is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 1,
  },

  // HAND TOOLS
  {
    id: 34,
    text: "Claw hammer is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 35,
    text: "Sledge hammer is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 36,
    text: "Rubber mallet is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 37,
    text: "Tape measure is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 38,
    text: "Speed square is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 39,
    text: "Framing square is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 40,
    text: "Combination square is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 41,
    text: "Torpedo level is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 42,
    text: "4-foot level is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 43,
    text: "Corner/post level is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 44,
    text: "Line level is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 45,
    text: "Chalk line reel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 46,
    text: "String line reel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 47,
    text: "Plumb bob is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 48,
    text: "Architect’s scale / measuring rule is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 49,
    text: "Story pole / grade rods set is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 50,
    text: "Carpenter’s pencil is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 51,
    text: "Utility knife is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 52,
    text: "Putty knife is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 53,
    text: "Cold chisel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 54,
    text: "Wood chisel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 55,
    text: "Nail set / center punch is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 56,
    text: "Block plane is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 57,
    text: "Wood rasp is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 58,
    text: "Metal file is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 59,
    text: "Flat bar / “wonder bar” (pry bar) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 60,
    text: "Cat’s paw nail puller is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 61,
    text: "Wire brush is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 62,
    text: "Flat-head screwdriver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 63,
    text: "Phillips-head screwdriver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 64,
    text: "Torx screwdriver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 65,
    text: "Adjustable (crescent) wrench is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 66,
    text: "Open-end wrench is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 67,
    text: "Box-end wrench is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 68,
    text: "Socket wrench / ratchet handle is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 69,
    text: "Slip-joint pliers are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 70,
    text: "Tongue-and-groove pliers (channel locks) are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 71,
    text: "Linesman pliers are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 72,
    text: "Diagonal cutters (dikes) are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 73,
    text: "Needle-nose pliers are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 74,
    text: "C-clamp is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 75,
    text: "Bar clamp is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 76,
    text: "Pipe wrench is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 77,
    text: "Hand saw (crosscut saw) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 78,
    text: "Backsaw / miter box saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 79,
    text: "Hacksaw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 80,
    text: "Coping saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 81,
    text: "Framing hammer is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 82,
    text: "Engineering hammer / single jack is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 83,
    text: "Ball peen hammer is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 84,
    text: "Dead blow mallet is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 85,
    text: "Wrecking bar / crow bar is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 86,
    text: "Robertson (square) screwdriver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 87,
    text: "6-in-1 screwdriver is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 88,
    text: "Folding ruler is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 89,
    text: "Mason’s line / dry line is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 90,
    text: "Locking pliers / Vise-Grips are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 91,
    text: "Spring clamp is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 92,
    text: "Breaker bar is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 93,
    text: "Allen / hex wrench set is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 94,
    text: "Framing chisel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 95,
    text: "Rip saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 96,
    text: "Hybrid hand saw is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 97,
    text: "Pointing trowel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 98,
    text: "Margin trowel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 99,
    text: "Finishing trowel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 100,
    text: "Gauging trowel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 101,
    text: "Bull float is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 102,
    text: "Hand float is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 103,
    text: "Edger (concrete edger) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 104,
    text: "Groover (concrete groover) is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 105,
    text: "Float trowel is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 106,
    text: "Concrete broom is a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
  {
    id: 107,
    text: "Snap ties are a:",
    options: ["Hand tool", "Power tool"],
    correctIndex: 0,
  },
];
